# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
